server:
  port: 8888

spring:
  application:
    name: ConfigService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo
          clone-on-start: true
          search-paths: '{application}'