server:
  port: 8888

spring:
  application:
    name: ConfigService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OussamaMahjour/ChatApplication.git
          default-label: Omar
          clone-on-start: true
          search-paths: services/configuration